<?php
/**
 * IdentificationsIdDocumentSecondaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * verify-u API
 *
 * # Introduction This API is documented in **OpenAPI 3.0 format**.  This API * enables a user to retrieve a list of the last 10 identifications * enables a user to retrieve profile data of a client's identification  # Basics * API calls have to be secured with HTTPS. * All data has to be submitted UTF-8 encoded. * The reply is sent JSON encoded.  # Authentication **verify-u** API uses Basic Authentication with secret key as username only.  Detailed information is provided at [Authentication](authentication)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * IdentificationsIdDocumentSecondaryTest Class Doc Comment
 *
 * @category    Class
 * @description Support document to the primary ID document
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class IdentificationsIdDocumentSecondaryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IdentificationsIdDocumentSecondary"
     */
    public function testIdentificationsIdDocumentSecondary()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "document_type"
     */
    public function testPropertyDocumentType()
    {
    }

    /**
     * Test attribute "expiration_date"
     */
    public function testPropertyExpirationDate()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "issue_date"
     */
    public function testPropertyIssueDate()
    {
    }

    /**
     * Test attribute "mrz"
     */
    public function testPropertyMrz()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }
}
